{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mysql-credentials",
   
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mysql-credentials",
       
        "creationTimestamp": null
      },
      "type": "Opaque",
      "data": null
    },
    "encryptedData": {
      "connection": "AgB9JRQf2h2LgHfbQSxv+y2bJzQFpDxs7thXIybBvKRr5nacWfubR0R+CN/KcL9rnakf1epDvZMofHXgz/RWIeBVzMyyb/ki+0loNSx9+jNs8fl8pMyCt28l6WNXx1aMFEESrqXqoVY2K1gLCdaVVBPUTJbbCa7GDQpeZroZPF15wk2DEQZkC>
      "password": "AgBtu0jWueol0io1hpGGIC8Da9/9HkilnvM4H2fkHPeI1dkQNcoS2Nc5LZCiIJUnQBReZQywzXy9oi8zCjIS7JPD895liOIxiUzm6KoT1GpHfqK9yYl6jFutTU7+8/8PxmfTmmp1k30k3hQ6YPSd2L7PirDpmZV8LTzX9HaHA1FI+BX/kJGh/Xi>
      "username": "AgCu6t6cKdGSIqT4coC5IEUyqmuuchCSL+E/8AnoImRUpfrvO934GlgwCvphBayavijoJSyWl+J2W4K/BWzYibeB4AOtvBU4qXNvJcrg3+Izs5BgVI6Os+d2o0ckVtZRvKvohxLIXdILE1FFgksZuvXQ6dvQpJfIJ+u5KUEjw+f9RZzvfaoBFqe>
    }
  }
}
